apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo-finally
  namespace: playground
spec:
  params:
    - name: appName
      type: string
  steps:
    - command:
        - /bin/bash
        - '-c'
        - echo
        - $(inputs.params.appName)
      image: registry.redhat.io/ubi7/ubi-minimal
      name: ''
      resources: {}
