apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: preflight-trigger
  namespace: playground
spec:
  params:
    - name: jobName
      type: string
    - name: jobConfigPath
      type: string
    - name: prowConfigPath
      type: string
    - name: ocpVersion
      type: string
    - name: pfltLogLevel
      type: string
    - name: pfltIndexImage
      type: string
    - name: pfltArtifacts
      type: string
    - name: testAsset
      type: string
    - name: assetType
      type: string
    - name: outputPath
      type: string
      params:
    - default: 'false'
      description: Skips preflight execution if set to "true"
      name: preflight_results_exists
      type: string
    - default: 'quay.io/opdev/preflight:0.0.0'
      description: Preflight image used
      name: base_image
      type: string
    - description: Package name for the Operator under test
      name: package_name
      type: string
    - description: Version of the bundle under test
      name: bundle_version
      type: string
    - description: The Operator index image which includes the bundle
      name: bundle_index_image
      type: string
    - description: The Operator bundle image under test
      name: bundle_image
      type: string
    - default: default
      description: The service account for the preflight config
      name: service_account
      type: string
    - default: default
      description: The namespace for the preflight config
      name: namespace
      type: string
    - default: trace
      description: Preflight logging level
      name: log_level
      type: string
  results:
    - description: ''
      name: log_output_file
    - description: ''
      name: result_output_file
    - description: ''
      name: artifacts_output_dir
  steps:
    - name: clone-for-configs
      image: registry.access.redhat.com/ubi8/go-toolset
      script: |
        #!/usr/bin/env bash
        echo "Cloning https://github.com/openshift/release"
        git clone https://github.com/openshift/release
      workingDir: $(workspaces.output.path)
    - args:
        - '-job-name'
        - 'periodic-ci-redhat-openshift-ecosystem-preflight-ocp-$(params.ocpVersion)-preflight-common-claim'
        - '-job-config-path'
        - 'release/ci-operator/jobs/redhat-openshift-ecosystem/preflight/redhat-openshift-ecosystem-preflight-ocp-$(params.ocpVersion)-periodics.yaml'
        - '-prow-config-path'
        - 'release/core-services/prow/02_config/_config.yaml'
        - '-ocp-version $(params.ocpVersion)'
        - '-pflt-artifacts'
        - '${SHARED_DIR}'
        - '-pflt-log-level'
        - '$(params.pfltLogLevel)'
        - '-pflt-index-image'
        - '$(params.pfltIndexImage)'
        - '-test-asset'
        - '$(params.testAsset)'
        - '-asset-type'
        - '$(params.assetType)'
        - '-output-path'
        - '${SHARED_DIR}'
      image: quay.io/opdev/preflight-trigger
      name: create-prowjob
      env:
        - name: KUBECONFIG
          value: $(workspaces.kubeconfig.path)/kubeconfig
  workspaces:
    - description: 'Storage for preflight results, logs and artifacts.'
      name: output
    - description: A kubernetes config for the cluster used in preflight testing
      name: kubeconfig
    - description: Docker config for retrieving the bundle image
      name: credentials
      optional: true